# Generated by Django 6.0.2 on 2026-02-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField()),
                ('pro_pic', models.ImageField(blank=True, null=True, upload_to='student_img/')),
                ('country', models.CharField()),
                ('message', models.TextField(max_length=200)),
            ],
        ),
    ]
